FROM node:22-alpine

RUN apk add --no-cache ffmpeg

ENV ENABLE_FRONTEND=true
ENV FRONTEND_PATH=/usr/local/lib/node_modules/video-chunk/frontend

RUN npm install -g video-chunk

RUN mkdir -p /test

COPY backend/tmp/Corrección_de_Pantalla_Verde_en_Video.mp4 /test/video.mp4

WORKDIR /test

CMD ["videoChunk", "--help"]